import 'package:flutter/material.dart';

const CustomIcons = <String, IconData> {
  
  'access_alarm': Icons.access_alarm,
  'access_time': Icons.access_time,
  'account_balance_wallet': Icons.account_balance_wallet,
  'airplanemode_active ': Icons.airplanemode_active,
  'airport_shuttle': Icons.airport_shuttle ,
  'all_inclusive': Icons.all_inclusive ,
  'assignment': Icons.assignment,
  'attach_money': Icons.attach_money,
  'audiotrack': Icons.audiotrack,
  'beach_access': Icons.beach_access ,
  'brightness_5': Icons.brightness_5,
  'brush': Icons.brush,
  'build': Icons.build,
  'business': Icons.business,
  'business_center': Icons.business_center,
  'cake': Icons.cake,
  'call': Icons.call,
  'camera_alt': Icons.camera_alt,
  'card_travel': Icons.card_travel,
  'chat_bubble_outline ': Icons.chat_bubble_outline ,
  'child_friendly ': Icons.child_friendly ,
  'code': Icons.code,
  'color_lens': Icons.color_lens,
  'computer': Icons.computer,
  'content_paste': Icons.content_paste,
  'crop_original': Icons.crop_original,
  'directions_bike': Icons.directions_bike ,
  'directions_car': Icons.directions_car ,
  'fastfood': Icons.fastfood,
  'favorite': Icons.favorite,
  'filter_vintage': Icons.filter_vintage ,
  'fitness_center': Icons.fitness_center,
  'flag': Icons.flag,
  'format_quote': Icons.format_quote,
  'grade': Icons.grade,
  'group': Icons.group,
  'hdr_strong': Icons.hdr_strong,
  'headset': Icons.headset ,
  'language': Icons.language ,
  'laptop_mac': Icons.laptop_mac ,
  'live_tv': Icons.live_tv ,
  'local_bar': Icons.local_bar ,
  'local_dining': Icons.local_dining ,
  'local_florist': Icons.local_florist ,
  'local_grocery_store': Icons.local_grocery_store ,
  'local_shipping': Icons.local_shipping ,
  'location_on': Icons.location_on ,
  'pets': Icons.pets ,
  'work': Icons.work 
  
};