class Lng {

  final Map<String,Map<String,String>> data = new Map<String,Map<String,String>>();
  Lng() {
    data.addAll({'English':en,'Myanmar':mm,'Zawgyi':zg});
  }

  String ts(String key, String lng){
    return data[lng][key] ?? '???';
  }
  
}

const en = <String, String>{
  'english': 'english',
  'myanmar': 'myanmar',
  'zawgyi': 'zawgyi(non standard font)',
  'monthly': 'monthly',
  'daily': 'daily',
  'transactions': 'transactions',
  'no_transation_desc': 'Currently no transactions',
  'press_add_new_transaction_desc': 'Press button to add new transaction.',
  'calendar': 'calendar',
  'settings': 'settings',
  'signout': 'sign out',
  'limit': 'Limit',
  'total': 'Total',
  'set_new_monthly': 'Set new monthly limit?',
  'set_new_daily': 'Set new daily limit?',
  'current_limit': 'Current limit',
  'delete_card': 'Delete this card?',
  'add_new': 'Add New',
  'your_title': 'Your Title',
  'amount': 'Amount', 
  'expense': 'Expense',
  'income': 'Income',
  'add_category': 'Add Card',
  'new_category': 'New Card',
  'add_category_desc': 'Cards will help you to group related transactions.',
  'category_name': 'Card Name',
  'create_category': 'Create New Card',
  'delete': 'Delete',
  'submit': 'Submit',
  'cancel': 'Cancel',
  'set_monthly_limit': 'Set Monthly Limit',
  'momthly_limit_desc': 'Put your monthly limit on the current card. (It can remind you, spending over limit in that card)',
  'set_daily_limit': 'Set Daily Limit',
  'set_daily_limit_desc': 'Put your daily limit on the current card. (It can remind you, spending over limit in that card)',
  'limit_amount': 'Limit Amount',
};

const mm = <String, String>{

'english': 'အင်္ဂလိပ်',
'myanmar': 'မြန်မာ',
'zawgyi': 'ဇော်ဂျီ(non standard font)',
'monthly': 'လစဥ်',
'daily': '‌နေ့စဉ်',
'transactions': 'စာရင်းများ',
'no_transation_desc': 'လက်ရှိစာရင်း မရှိသေးပါ',
'press_add_new_transaction_desc': 'စာရင်းအသစ်သွင်းရန်အပေါင်း ခလုတ်ကိုနှိပ်ပါ',
'calendar': 'ပြက္ခဒိန်',
'settings': 'ပြုပြင်‌ပြောင်းလဲရန်',
'signout': 'ထွက်ခွာရန်',
'limit': 'ကန့်သတ်ချက်',
'total': 'စုစု‌ပေါင်း',
'set_new_monthly': 'လစဉ်ကန့်သတ်ချက်လုပ်မည်?',
'set_new_daily': 'နေ့စဉ်ကန့်သတ်ချက်လုပ်မည်?',
'current_limit': 'လက်ရှိကန့်သတ်ချက်',
'delete_card': 'ယခု ကတ်ကိုဖျက်မည်?',
'add_new': 'အသစ်ထည့်မည်',
'your_title': 'အကြောင်းအရာ‌ခေါင်းစဉ်',
'amount': 'ပမာဏ',
'expense': 'ထွက်‌ငွေ',
'income': 'ဝင်‌ငွေ',
'add_category': 'ကတ်အသစ်ထည့်ရန်',
'new_category': 'ကတ်အသစ်',
'add_category_desc': 'ကတ်များပြုလုပ်ပြီး ဆက်စပ်သော စာရင်းများကို စုပေါင်းသိမ်းဆည်းနိုင်ပါသည်.',
'category_name': 'ကတ်အမည်',
'create_category': 'ကတ်အသစ်ပြုလုပ်ရန်',
'delete': 'ဖျက်ပစ်မည်',
'submit': 'ထည့်သွင်းမည်',
'cancel': 'မလုပ်‌တော့ပါ',
'set_monthly_limit': 'လစဥ်ကန့်သတ်ချက်ထည့်ရန်',
'momthly_limit_desc': 'လစဥ်ကန့်သတ်ချက်ပမာဏကိုထည့်သွင်းပါ (သတ်မှတ်ချက်ထက်ပိုမသုံးမိစေရန် သတိပေးနိုင်ရန်ဖြစ်ပါသည်)',
'set_daily_limit': '‌နေ့စဥ်ကန့်သတ်ချက်ထည့်ရန်',
'set_daily_limit_desc':'‌နေ့စဉ်ကန့်သတ်ချက်ပမာဏကိုထည့်သွင်းပါ (သတ်မှတ်ချက်ထက်ပိုမသုံးမိစေရန် သတိပေးနိုင်ရန်ဖြစ်ပါသည်)',
'limit_amount': 'ကန့်သတ်ချက်ပမာဏ',
};

const zg = <String, String>{
  'english': 'အဂၤလိပ္',
'myanmar': 'ျမန္မာ',
'zawgyi': 'ေဇာ္ဂ်ီ(non standard font)',
'monthly': 'လစဥ္',
'daily': '‌ေန႔စဥ္',
'transactions': 'စာရင္းမ်ား',
'no_transation_desc': 'လက္ရွိစာရင္း မရွိေသးပါ',
'press_add_new_transaction_desc': 'စာရင္းအသစ္သြင္းရန္အေပါင္း ခလုတ္ကိုႏွိပ္ပါ',
'calendar': 'ျပကၡဒိန္',
'settings': 'ျပဳျပင္‌ေျပာင္းလဲရန္',
'signout': 'ထြက္ခြာရန္',
'limit': 'ကန္႔သတ္ခ်က္',
'total': 'စုစု‌ေပါင္း',
'set_new_monthly': 'လစဥ္ကန႔္သတ္ခ်က္လုပ္မည္?',
'set_new_daily': 'ေန႔စဥ္ကန႔္သတ္ခ်က္လုပ္မည္?',
'current_limit': 'လက္ရွိကန္႔သတ္ခ်က္',
'delete_card': 'ယခု ကတ္ကိုဖ်က္မည္?',
'add_new': 'အသစ္ထည့္မည္',
'your_title': 'အေၾကာင္းအရာ‌ေခါင္းစဥ္',
'amount': 'ပမာဏ',
'expense': 'ထြက္‌ေငြ',
'income': 'ဝင္‌ေငြ',
'add_category': 'ကတ္အသစ္ထည့္ရန္',
'new_category': 'ကတ္အသစ္',
'add_category_desc': 'ကတ္မ်ားျပဳလုပ္ၿပီး ဆက္စပ္ေသာ စာရင္းမ်ားကို စုေပါင္းသိမ္းဆည္းႏိုင္ပါသည္.',
'category_name': 'ကတ္အမည္',
'create_category': 'ကတ္အသစ္ျပဳလုပ္ရန္',
'delete': 'ဖ်က္ပစ္မည္',
'submit': 'ထည့္သြင္းမည္',
'cancel': 'မလုပ္‌ေတာ့ပါ',
'set_monthly_limit': 'လစဥ္ကန္႔သတ္ခ်က္ထည့္ရန္',
'momthly_limit_desc': 'လစဥ္ကန႔္သတ္ခ်က္ပမာဏကိုထည့္သြင္းပါ (သတ္မွတ္ခ်က္ထက္ပိုမသုံးမိေစရန္ သတိေပးႏိုင္ရန္ျဖစ္ပါသည္)',
'set_daily_limit': '‌ေန႔စဥ္ကန္႔သတ္ခ်က္ထည့္ရန္',
'set_daily_limit_desc':'‌ေန႔စဥ္ကန႔္သတ္ခ်က္ပမာဏကိုထည့္သြင္းပါ (သတ္မွတ္ခ်က္ထက္ပိုမသုံးမိေစရန္ သတိေပးႏိုင္ရန္ျဖစ္ပါသည္)',
'limit_amount': 'ကန္႔သတ္ခ်က္ပမာဏ',
};
